/* CREATE TABELS */

USE [WEXO_GreetMe]
GO

insert into people (full_name, date_of_birth, hiring_date, email) values ('Aryn Marskell', '11/18/1984', '10/20/1992', 'amarskell0@howstuffworks.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Ozzie Grishechkin', '1/14/1992', '1/24/1996', 'ogrishechkin1@theatlantic.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Pierson Juan', '2/8/1967', '6/13/2002', 'pjuan2@stumbleupon.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Robenia Trevithick', '4/25/2000', '9/23/1999', 'rtrevithick3@wsj.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Janine Node', '12/31/1974', '10/11/1990', 'jnode4@scribd.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Davidson Markushkin', '2/1/1960', '11/4/1995', 'dmarkushkin5@360.cn');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Gustavo Gatecliff', '2/7/1974', '2/2/1990', 'ggatecliff6@cyberchimps.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Pieter Stucksbury', '10/20/1991', '3/5/1993', 'pstucksbury7@pagesperso-orange.fr');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Janel Pighills', '11/24/1963', '7/4/1991', 'jpighills8@wp.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Genia Jelly', '8/6/1996', '12/22/1995', 'gjelly9@nps.gov');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Burton Pocock', '8/16/1984', '8/24/2001', 'bpococka@berkeley.edu');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Wadsworth Waterland', '1/8/1988', '11/8/2001', 'wwaterlandb@blogspot.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Eva Broz', '3/15/1994', '4/22/1996', 'ebrozc@altervista.org');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Aida Gomer', '1/7/1970', '7/10/1996', 'agomerd@cbsnews.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Edie McTrustey', '12/7/1996', '4/4/1990', 'emctrusteye@google.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Cayla Bonass', '3/9/1963', '12/25/1999', 'cbonassf@multiply.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Ambrosi Hamill', '12/22/1992', '9/26/1994', 'ahamillg@aboutads.info');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Gunar Cartan', '8/23/1963', '8/10/1995', 'gcartanh@skype.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Babb Craigs', '9/23/1992', '1/11/1992', 'bcraigsi@pinterest.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Onofredo Parks', '8/6/2000', '3/4/1997', 'oparksj@unblog.fr');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Scott Brundle', '8/24/1986', '1/11/1996', 'sbrundlek@europa.eu');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Steffie Doughartie', '12/18/1974', '5/7/1999', 'sdoughartiel@webs.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Eldridge McLafferty', '2/25/1996', '4/14/1990', 'emclaffertym@devhub.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Danyette Railton', '12/14/2000', '10/10/2000', 'drailtonn@prnewswire.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Marcille Shoard', '2/23/1960', '2/18/1998', 'mshoardo@dagondesign.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Emilio Hammer', '10/26/1970', '12/29/1991', 'ehammerp@foxnews.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Adrian Blampied', '11/17/1995', '4/20/1998', 'ablampiedq@pinterest.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Cecile Hadgkiss', '12/29/1982', '9/18/1992', 'chadgkissr@ovh.net');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Leese Bride', '1/22/2000', '3/17/1993', 'lbrides@netvibes.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Rik Giraux', '3/6/1965', '12/7/1991', 'rgirauxt@ibm.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Afton Mauger', '4/28/1965', '1/2/1994', 'amaugeru@usda.gov');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Fanchette Guilfoyle', '7/11/1970', '8/20/2001', 'fguilfoylev@booking.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Issy Windley', '12/25/1986', '7/31/1997', 'iwindleyw@wikimedia.org');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Alyssa Milby', '5/16/1989', '9/2/1990', 'amilbyx@163.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Maurie Louthe', '1/1/1981', '11/10/1995', 'mlouthey@constantcontact.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Chloris Loxley', '5/10/1976', '4/7/1991', 'cloxleyz@eventbrite.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Thadeus Orteu', '6/19/1984', '8/12/1993', 'torteu10@nbcnews.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Addi Vasilenko', '4/19/1979', '2/9/1997', 'avasilenko11@vkontakte.ru');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Teodorico Arens', '4/22/1973', '4/1/2000', 'tarens12@pbs.org');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Keven Isted', '5/8/1998', '10/27/1995', 'kisted13@theglobeandmail.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Howie Yerrell', '11/3/1976', '2/6/1991', 'hyerrell14@diigo.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Lonni Stairmond', '9/18/1994', '5/19/1992', 'lstairmond15@wordpress.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Bird Embling', '11/16/1971', '6/30/1993', 'bembling16@arizona.edu');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Howie Ruzicka', '10/24/2000', '8/9/1996', 'hruzicka17@is.gd');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Boycie Cordier', '7/7/1978', '4/18/1992', 'bcordier18@yolasite.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Lindie Menichini', '11/24/1986', '10/14/1992', 'lmenichini19@mapy.cz');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Burk Harry', '12/20/1989', '2/7/1996', 'bharry1a@globo.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Arlena Hullot', '8/6/1974', '11/2/1998', 'ahullot1b@scribd.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Rebecca Jentet', '10/14/1975', '12/25/1999', 'rjentet1c@nature.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Thornton Taffurelli', '5/23/1983', '8/26/2000', 'ttaffurelli1d@cbc.ca');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Dion Marden', '12/27/1960', '11/8/1992', 'dmarden1e@freewebs.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Lorine Drayson', '1/24/1972', '9/1/1997', 'ldrayson1f@hao123.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Christos Di Carlo', '12/6/1998', '5/12/2000', 'cdi1g@freewebs.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Monah Rainer', '9/20/1963', '11/20/1990', 'mrainer1h@washington.edu');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Dorella Monier', '6/22/2000', '7/26/1991', 'dmonier1i@smugmug.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Mariska Craigmile', '3/13/1976', '8/30/1995', 'mcraigmile1j@disqus.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Inigo MacKimmie', '10/3/1983', '12/14/2000', 'imackimmie1k@nature.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Mame Sandars', '7/30/1968', '2/5/1996', 'msandars1l@theguardian.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Elizabeth Hicks', '8/4/1999', '8/26/1995', 'ehicks1m@cafepress.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Moishe Willgrass', '10/16/1988', '3/31/1991', 'mwillgrass1n@twitter.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Augustine Huckstepp', '1/8/1989', '2/24/1997', 'ahuckstepp1o@businesswire.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Hurley Shillaber', '11/13/1968', '6/23/1996', 'hshillaber1p@mysql.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Barbara Hallihan', '12/13/1964', '7/12/1995', 'bhallihan1q@barnesandnoble.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Germain Tarrier', '10/21/1996', '6/29/1996', 'gtarrier1r@amazon.co.uk');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Sutherlan Hurlston', '1/14/1975', '12/5/2000', 'shurlston1s@symantec.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Kelcie Liggett', '4/1/1994', '8/22/2002', 'kliggett1t@chronoengine.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Tove Leaver', '7/12/1965', '4/18/1999', 'tleaver1u@chronoengine.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Kean Branigan', '8/20/1991', '5/27/1997', 'kbranigan1v@ihg.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Osbert Jonson', '2/3/1972', '5/6/1999', 'ojonson1w@elpais.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Adam Guillard', '8/5/2000', '3/30/1991', 'aguillard1x@nature.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Bron Fierro', '7/8/1979', '9/9/1992', 'bfierro1y@auda.org.au');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Pammy Moodey', '3/27/1972', '5/9/1994', 'pmoodey1z@thetimes.co.uk');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Madel Gerb', '12/1/1969', '7/25/1998', 'mgerb20@bigcartel.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Ulberto Salla', '1/28/1967', '2/22/1994', 'usalla21@barnesandnoble.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Daven Greenhill', '5/24/1989', '3/11/1994', 'dgreenhill22@opensource.org');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Rodge Barrat', '1/3/1977', '12/15/1991', 'rbarrat23@privacy.gov.au');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Korie Brettoner', '12/16/1970', '2/15/2002', 'kbrettoner24@nps.gov');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Darb Greatreax', '2/8/2000', '1/12/1993', 'dgreatreax25@gizmodo.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Alden Zumbusch', '1/16/1965', '6/8/1998', 'azumbusch26@google.com.br');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Bobine Weepers', '2/17/1974', '12/13/2001', 'bweepers27@addtoany.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Demetris Megarry', '4/10/1962', '12/18/1990', 'dmegarry28@hud.gov');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Teresina Stobo', '6/6/2000', '2/5/1997', 'tstobo29@barnesandnoble.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Lorrayne Vauls', '2/13/1989', '11/3/2002', 'lvauls2a@cafepress.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Adele McBrearty', '5/10/2000', '1/3/2000', 'amcbrearty2b@indiatimes.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Rustie Jobke', '9/30/1985', '5/17/1991', 'rjobke2c@ted.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Prince Amort', '2/22/1969', '5/9/2001', 'pamort2d@smh.com.au');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Carey Burtenshaw', '6/5/1965', '11/8/1996', 'cburtenshaw2e@constantcontact.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Reynold Hauxby', '6/22/1983', '6/10/1991', 'rhauxby2f@npr.org');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Odey Whorlow', '8/12/1960', '4/12/1997', 'owhorlow2g@ed.gov');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Daloris Springall', '10/28/1984', '11/16/1994', 'dspringall2h@nature.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Nada Minchella', '8/31/1990', '10/22/1990', 'nminchella2i@jigsy.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Alexine Sanper', '2/9/1979', '7/6/1990', 'asanper2j@sohu.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Edin Channing', '7/18/1998', '4/2/1995', 'echanning2k@sphinn.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Arabele Doey', '5/9/1983', '3/15/1996', 'adoey2l@scientificamerican.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Winthrop Eggerton', '6/1/1986', '10/25/1996', 'weggerton2m@mlb.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Kare Cocker', '2/25/1973', '9/6/2000', 'kcocker2n@biglobe.ne.jp');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Ida Stapforth', '11/22/1990', '8/15/1994', 'istapforth2o@pagesperso-orange.fr');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Farah Piller', '10/27/1970', '6/6/1997', 'fpiller2p@earthlink.net');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Caroljean Kennard', '8/23/1967', '9/5/1992', 'ckennard2q@geocities.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Gilles Gutteridge', '12/22/1995', '1/26/1999', 'ggutteridge2r@slideshare.net');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Maegan Georges', '8/2/1994', '2/18/1994', 'mgeorges2s@moonfruit.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Reinald Farrah', '8/10/1963', '7/25/1995', 'rfarrah2t@soup.io');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Lula Setterfield', '6/1/1970', '1/31/1992', 'lsetterfield2u@google.ru');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Elnore Giacovetti', '4/18/1994', '1/26/2001', 'egiacovetti2v@plala.or.jp');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Matt Maylour', '9/1/1994', '7/7/1990', 'mmaylour2w@marketwatch.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Quincey Kochs', '9/28/1994', '10/4/2002', 'qkochs2x@nsw.gov.au');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Tomkin Palumbo', '10/23/2000', '11/24/2001', 'tpalumbo2y@imageshack.us');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Yancy Bockings', '3/5/1990', '1/24/1993', 'ybockings2z@yolasite.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Winne Stallen', '4/13/1960', '8/29/1994', 'wstallen30@bigcartel.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Reena Tuftin', '1/25/1966', '7/1/2002', 'rtuftin31@lycos.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Sylvan Hulls', '4/22/1996', '8/17/1997', 'shulls32@sciencedaily.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Constantia Faucherand', '9/10/1968', '3/28/1995', 'cfaucherand33@house.gov');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Ruthi Mugridge', '9/21/1998', '2/28/1999', 'rmugridge34@i2i.jp');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Marchelle Ropkins', '12/30/1998', '7/2/1995', 'mropkins35@lycos.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Cassius Mauchlen', '11/16/1972', '5/4/1995', 'cmauchlen36@opera.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Currey Alcoran', '4/13/1976', '11/8/1997', 'calcoran37@unc.edu');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Dillon Simons', '11/5/1963', '11/29/1991', 'dsimons38@vkontakte.ru');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Rosemonde Brixey', '3/22/1963', '7/5/1993', 'rbrixey39@adobe.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Giacomo Batt', '5/12/1976', '3/4/2000', 'gbatt3a@msn.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Charity Ferrieres', '1/28/1967', '8/20/2001', 'cferrieres3b@indiatimes.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Dannel Patridge', '10/5/1990', '2/6/1995', 'dpatridge3c@bloomberg.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Cull Welsby', '2/9/1970', '10/24/1990', 'cwelsby3d@delicious.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Allyn Brownsall', '1/9/1964', '2/28/1998', 'abrownsall3e@e-recht24.de');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Elle Stanesby', '1/13/1960', '10/2/1993', 'estanesby3f@tripod.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Kennan Jime', '5/24/1987', '9/9/2002', 'kjime3g@skype.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Theodora Muttock', '2/23/1976', '10/28/2002', 'tmuttock3h@europa.eu');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Alane Fenemore', '9/19/1960', '1/14/1994', 'afenemore3i@hostgator.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Glenn Stapford', '1/26/1968', '10/18/1999', 'gstapford3j@weebly.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Jenelle Comino', '3/13/1987', '10/6/2002', 'jcomino3k@flickr.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Toddie Eassom', '1/1/1999', '1/2/2002', 'teassom3l@usatoday.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Ailyn Rosendahl', '11/4/1990', '5/8/1997', 'arosendahl3m@europa.eu');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Ewart Bartak', '11/4/1998', '3/25/2001', 'ebartak3n@seesaa.net');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Helene Rickis', '6/8/1989', '5/1/1997', 'hrickis3o@theglobeandmail.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Ross Linnett', '4/22/1984', '12/17/2000', 'rlinnett3p@pbs.org');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Olympia McKelvie', '1/21/1986', '11/17/1997', 'omckelvie3q@paginegialle.it');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Birdie Orritt', '9/20/1963', '5/30/2002', 'borritt3r@japanpost.jp');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Clarice Flagg', '5/5/1982', '6/2/1999', 'cflagg3s@i2i.jp');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Fred Gwyn', '9/14/1992', '12/24/1990', 'fgwyn3t@digg.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Erv Tring', '11/21/1960', '11/24/2002', 'etring3u@prnewswire.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Lesli Stollard', '5/1/1967', '7/29/1992', 'lstollard3v@cisco.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Bettye Dearth', '1/8/1996', '4/10/1997', 'bdearth3w@disqus.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Kaylee Dodswell', '9/19/1985', '8/8/1999', 'kdodswell3x@army.mil');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Sheree Kubanek', '5/15/1976', '2/14/1997', 'skubanek3y@sciencedaily.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Ceciley Bamfield', '7/10/1982', '5/15/2001', 'cbamfield3z@omniture.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Teressa Conradsen', '8/22/1999', '2/21/1994', 'tconradsen40@behance.net');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Sacha McIlmurray', '11/4/1983', '9/28/1998', 'smcilmurray41@princeton.edu');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Vernice Ausello', '3/3/1995', '7/29/1995', 'vausello42@lycos.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Ricardo Dunmore', '4/26/1981', '11/27/1994', 'rdunmore43@redcross.org');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Haskel Minucci', '6/18/1996', '3/27/1998', 'hminucci44@usnews.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Cairistiona Barthrop', '9/16/1972', '4/13/2002', 'cbarthrop45@ebay.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Biron Baggot', '6/28/1983', '9/18/1996', 'bbaggot46@php.net');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Hayley Chiese', '3/8/2000', '7/16/1998', 'hchiese47@cnet.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Cristobal Showell', '8/19/1982', '8/29/1997', 'cshowell48@homestead.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Etienne Varnals', '12/16/1999', '5/10/1999', 'evarnals49@netscape.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Roldan Wenn', '9/6/1981', '9/5/2002', 'rwenn4a@mail.ru');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Ailey Dalbey', '1/26/1983', '8/16/1999', 'adalbey4b@163.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Ashlee Humpherston', '11/17/1988', '6/11/1996', 'ahumpherston4c@mapy.cz');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Lucine Goodbur', '9/12/1960', '5/4/1993', 'lgoodbur4d@printfriendly.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Gery Bande', '2/12/1999', '4/4/1997', 'gbande4e@google.com.br');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Diann Bleas', '6/11/1987', '6/14/1992', 'dbleas4f@springer.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Marlow Simmank', '12/12/1989', '1/12/1992', 'msimmank4g@dedecms.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Eulalie Jirek', '7/9/1985', '6/18/1997', 'ejirek4h@photobucket.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Carmelle Khrishtafovich', '9/23/1989', '6/9/1996', 'ckhrishtafovich4i@prnewswire.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Brunhilde Bunclark', '11/30/2000', '2/17/1993', 'bbunclark4j@flickr.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Dorotea Kristof', '4/6/1977', '5/29/1993', 'dkristof4k@state.gov');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Alanson Fosserd', '9/27/1999', '2/17/1993', 'afosserd4l@taobao.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Liuka Viegas', '7/20/1998', '12/26/1990', 'lviegas4m@hatena.ne.jp');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Isidora Creamer', '7/14/1970', '5/15/1998', 'icreamer4n@mayoclinic.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Kesley Carluccio', '4/16/1990', '2/19/1993', 'kcarluccio4o@economist.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Mikel Molohan', '11/28/1983', '12/19/2002', 'mmolohan4p@reverbnation.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Natty Von Der Empten', '6/3/1988', '7/22/1992', 'nvon4q@loc.gov');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Dodie Rapport', '11/23/1988', '10/8/2000', 'drapport4r@va.gov');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Brendan Munday', '7/11/1977', '7/31/2000', 'bmunday4s@symantec.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Carline Cuddon', '3/10/1980', '8/21/1991', 'ccuddon4t@dedecms.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Thorpe Gowman', '6/14/1985', '7/28/1999', 'tgowman4u@uiuc.edu');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Tressa Rubroe', '9/21/1966', '3/6/1993', 'trubroe4v@cornell.edu');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Edik Perri', '9/14/1964', '7/8/1998', 'eperri4w@newsvine.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Tito Grigorescu', '11/5/1972', '12/26/1993', 'tgrigorescu4x@delicious.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Thorvald Blackader', '7/14/1971', '5/6/1999', 'tblackader4y@seesaa.net');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Goldina Elce', '3/26/1989', '7/29/1990', 'gelce4z@blogger.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Robinson Frankiss', '7/3/1988', '12/18/1990', 'rfrankiss50@shop-pro.jp');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Feliza Yarnley', '2/28/1979', '4/19/1998', 'fyarnley51@ezinearticles.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Bunny Calderwood', '4/19/1965', '11/6/2002', 'bcalderwood52@comsenz.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Pancho Sisse', '12/27/1961', '4/30/1993', 'psisse53@4shared.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Aeriela Stealfox', '7/31/1962', '12/19/1990', 'astealfox54@digg.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Georgena Juanico', '9/15/1965', '10/5/1995', 'gjuanico55@free.fr');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Daveen Gillimgham', '6/30/1997', '6/15/2000', 'dgillimgham56@i2i.jp');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Arvie Robbings', '5/6/1982', '2/16/2001', 'arobbings57@newyorker.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Hollie Christoffersen', '11/23/1990', '2/17/2001', 'hchristoffersen58@shutterfly.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Hertha Beceril', '10/4/1989', '3/27/2001', 'hbeceril59@bing.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Chicky Hammerton', '9/19/1984', '12/11/1997', 'chammerton5a@hatena.ne.jp');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Reiko Randles', '6/15/1961', '5/14/1997', 'rrandles5b@google.pl');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Tierney Drewery', '5/7/1994', '5/23/1990', 'tdrewery5c@biblegateway.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Michell Labrenz', '1/25/1968', '8/18/1991', 'mlabrenz5d@cbsnews.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Rocky O''Quin', '1/20/1978', '6/8/1991', 'roquin5e@ted.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Tabor Swainsbury', '5/12/1983', '9/20/2001', 'tswainsbury5f@go.com');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Darlleen Carlson', '11/22/1997', '9/11/1996', 'dcarlson5g@free.fr');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Elva Saile', '4/14/1989', '12/25/1995', 'esaile5h@google.co.uk');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Caresse Groundwator', '5/8/1960', '4/17/1999', 'cgroundwator5i@npr.org');
insert into people (full_name, date_of_birth, hiring_date, email) values ('Orlando Corkill', '4/30/1985', '1/30/1990', 'ocorkill5j@sina.com.cn');

GO

insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Kuhn LLC View', true, false, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Strosin-Witting View', false, true, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Morissette, Baumbach and Williamson View', true, true, false, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Quigley, Shanahan and Grant View', false, false, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Nitzsche LLC View', false, false, true, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Luettgen, Homenick and Watsica View', false, false, true, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Schmitt Inc View', true, true, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Paucek and Sons View', false, false, false, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Kutch, Crist and Quigley View', true, false, true, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Toy, Schmitt and Rogahn View', true, true, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Swaniawski, Jacobson and Keebler View', true, true, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Wehner Group View', true, true, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Howell, Leuschke and Rice View', false, false, false, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Stoltenberg, MacGyver and Wuckert View', true, true, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Mayer-Rowe View', false, true, true, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Hoeger-Durgan View', false, false, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Romaguera Group View', true, false, false, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Thiel Inc View', true, true, true, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Keeling and Sons View', true, true, false, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Ratke-Beatty View', false, true, true, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Harvey and Sons View', false, true, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Nitzsche-Gaylord View', false, false, true, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Altenwerth, Wyman and Mitchell View', false, true, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Nitzsche Group View', false, false, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Parker-Walsh View', false, false, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Sawayn-Nitzsche View', false, true, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Brown-Greenholt View', true, false, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Hoppe, Wilkinson and Herzog View', true, true, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Beahan, Kertzmann and Kreiger View', false, false, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Hilpert-Adams View', true, false, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Bechtelar LLC View', true, false, true, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Gerhold Inc View', true, false, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Ziemann-Thompson View', false, true, false, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Morissette Inc View', true, true, false, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Kiehn-Ernser View', false, false, true, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Zieme-Wisoky View', false, true, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Gusikowski-Block View', true, false, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Ortiz LLC View', false, false, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Wiegand, Hintz and O''Keefe View', true, true, true, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Ruecker Group View', true, true, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Koss-Schuster View', true, false, true, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Paucek, Champlin and Hoeger View', false, false, true, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Gorczany, Satterfield and Bernier View', false, true, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Swaniawski and Sons View', false, false, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Mertz, Stanton and Ruecker View', true, false, true, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Kris, Mante and Marks View', false, false, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Lindgren, Kautzer and Nitzsche View', true, false, true, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Zboncak LLC View', true, false, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Graham-Johns View', true, true, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Paucek and Sons View', false, true, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Reynolds, Hagenes and Romaguera View', false, true, false, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Orn-Krajcik View', true, true, true, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Welch, Ankunding and Wilkinson View', false, true, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Lehner and Sons View', false, true, true, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Wolff Inc View', false, true, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Witting, Marks and Rohan View', true, true, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Hudson-Steuber View', true, true, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Koch, Greenholt and Stamm View', false, false, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Rutherford Group View', true, true, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Schaefer-Bayer View', true, true, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Schmitt-Schmeler View', true, false, false, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('West, Franecki and Sawayn View', false, false, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Nader-Windler View', true, true, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Schoen LLC View', true, true, false, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Baumbach-Streich View', false, true, false, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Feest-Crona View', true, true, true, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Medhurst-Morar View', true, false, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Sawayn LLC View', false, false, false, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Okuneva-Dibbert View', false, false, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Greenfelder-Simonis View', false, true, true, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Kreiger-Krajcik View', true, false, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('O''Connell-Carter View', false, false, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Braun and Sons View', true, false, false, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Pagac LLC View', true, true, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Dickens and Sons View', false, true, false, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Wuckert, Leffler and Mohr View', true, true, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Mohr LLC View', false, false, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Smith-Prosacco View', false, true, true, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Kreiger, Witting and Hammes View', true, true, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Buckridge Group View', false, false, false, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Bernier and Sons View', false, true, false, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Herzog, O''Conner and Olson View', false, true, true, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Rau-Jakubowski View', false, false, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Berge Inc View', false, false, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Schmeler Group View', false, true, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Collier Group View', false, false, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Funk, Lang and Schaefer View', false, true, true, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Abshire-Herzog View', false, true, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Ondricka Inc View', false, false, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Baumbach, Armstrong and Pouros View', false, false, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Goldner-Christiansen View', true, true, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Yost-Crist View', false, true, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Smitham and Sons View', true, false, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('McKenzie and Sons View', true, false, false, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Strosin, Schulist and Hoeger View', true, false, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Bernhard LLC View', true, false, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Kiehn-Emmerich View', false, false, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Hauck Inc View', false, false, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Gutmann-Dickens View', false, false, false, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Paucek LLC View', false, false, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Willms Inc View', false, true, false, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Conn, Wolff and Gaylord View', false, false, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Weimann, Stark and McDermott View', false, true, false, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Hane Group View', false, true, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Kihn LLC View', false, false, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Sipes Inc View', false, true, false, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Kuhlman-Champlin View', true, false, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Aufderhar-Rodriguez View', false, false, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Rosenbaum, Douglas and Sanford View', false, true, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Champlin and Sons View', false, false, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Kihn-Berge View', true, true, true, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Goldner Group View', false, true, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Maggio and Sons View', false, false, true, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Rath-Kuhn View', false, true, true, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Fay, Heathcote and Buckridge View', true, true, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Kihn LLC View', true, true, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Casper-Weissnat View', false, false, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Lemke, Koss and Gorczany View', false, false, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Koepp Inc View', false, true, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Weimann and Sons View', false, true, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Waters, Jerde and Rutherford View', false, false, true, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Morissette Inc View', true, false, true, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Streich and Sons View', false, false, false, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Simonis, Kuhic and Sawayn View', false, false, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Monahan-Renner View', true, false, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Cassin and Sons View', false, false, true, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Stroman-Treutel View', false, false, false, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Gulgowski, Bednar and Stroman View', true, true, true, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Schoen-Runolfsson View', false, false, false, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Tremblay Group View', false, false, true, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Marks, McClure and McClure View', false, false, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Bauch, Ritchie and Trantow View', true, true, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Jacobson-Rogahn View', true, false, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Goyette, Johns and Crona View', true, true, false, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Schuppe and Sons View', false, true, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Howell Inc View', true, false, true, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Luettgen-Champlin View', false, true, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Bashirian Group View', true, true, false, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Senger-Kerluke View', false, false, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Wolf, Carroll and Mosciski View', false, true, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Gleichner Group View', true, false, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Nolan, Dare and Howe View', false, true, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Berge-McDermott View', false, false, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Ebert-Douglas View', false, false, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Koch, Sawayn and Collier View', true, false, true, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Emard, Paucek and Hessel View', true, false, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Skiles-Mann View', true, true, true, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Becker-Kuphal View', true, false, true, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Kilback Group View', false, true, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Ebert-Schmeler View', true, true, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Koepp-Beatty View', false, true, false, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Hilll-Dare View', false, true, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Grant, Stroman and Schmitt View', true, false, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Hauck-Hammes View', false, true, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Kuphal LLC View', true, false, true, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Kertzmann-Wunsch View', false, false, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Tillman, Labadie and Parker View', false, true, false, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Weimann-Hudson View', true, true, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Labadie, Goyette and Padberg View', false, false, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Bailey-Murphy View', false, true, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Harber-Friesen View', false, false, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Fadel-Bosco View', true, true, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Raynor-Corwin View', true, true, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Torp, Collier and Hilll View', true, false, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Kunde Group View', true, true, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Leannon, Kemmer and Balistreri View', true, false, true, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Berge Group View', true, false, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Langworth and Sons View', true, false, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Wehner-Runte View', false, false, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Turner-Gleason View', false, false, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Schowalter, Harris and Simonis View', false, true, true, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Conn, Toy and Sipes View', true, false, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Torphy-Graham View', false, true, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Nitzsche and Sons View', false, true, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Donnelly-Wisoky View', true, false, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Smith and Sons View', false, true, false, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Baumbach-Reynolds View', false, true, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Morar, Cole and Lakin View', true, true, false, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Shanahan, Barrows and Johnson View', false, false, false, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Simonis Group View', true, false, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Fritsch, Rogahn and Mann View', false, false, true, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Wunsch Inc View', false, true, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Schroeder-Walker View', true, false, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Streich-Gibson View', true, true, false, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Lang-Heller View', true, false, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Kreiger and Sons View', true, false, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Wyman and Sons View', false, false, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Hammes LLC View', true, false, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Rolfson, Botsford and Simonis View', true, false, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('O''Keefe Group View', false, false, false, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Hessel and Sons View', true, false, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Collier-Murazik View', false, true, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Lindgren and Sons View', true, true, false, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Morar-Christiansen View', false, true, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Kub, Bednar and Fadel View', true, true, true, false);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Jones and Sons View', true, true, true, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Rippin Inc View', false, true, true, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Lakin-Marvin View', false, false, true, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Bins-Stiedemann View', false, false, true, true);
insert into [views] (view_name, has_current_datetime, has_birthday, has_anniversary, has_menu) values ('Grady and Sons View', false, true, true, true);

GO

insert into screens (screen_name, view_id) values ('Strosin-Turner Screen', 3);
insert into screens (screen_name, view_id) values ('Metz, Ernser and Bruen Screen', 54);
insert into screens (screen_name, view_id) values ('Hudson, Turcotte and Mayert Screen', 4);
insert into screens (screen_name, view_id) values ('Dietrich, Sanford and Rempel Screen', 27);
insert into screens (screen_name, view_id) values ('Glover LLC Screen', 29);
insert into screens (screen_name, view_id) values ('Johns-Ortiz Screen', 25);
insert into screens (screen_name, view_id) values ('Kuhlman, Mann and Leuschke Screen', 4);
insert into screens (screen_name, view_id) values ('Gaylord, Kertzmann and Wolff Screen', 49);
insert into screens (screen_name, view_id) values ('Berge-Bogan Screen', 85);
insert into screens (screen_name, view_id) values ('Boyer, Schmeler and Prosacco Screen', 50);
insert into screens (screen_name, view_id) values ('Rohan, Orn and Leannon Screen', 10);
insert into screens (screen_name, view_id) values ('Harvey-Altenwerth Screen', 62);
insert into screens (screen_name, view_id) values ('Dickinson, Pfeffer and Keebler Screen', 7);
insert into screens (screen_name, view_id) values ('Nicolas, Russel and Ryan Screen', 70);
insert into screens (screen_name, view_id) values ('Klein, Langosh and Pfeffer Screen', 9);
insert into screens (screen_name, view_id) values ('Kiehn Group Screen', 49);
insert into screens (screen_name, view_id) values ('Pouros, Stroman and Parker Screen', 44);
insert into screens (screen_name, view_id) values ('Breitenberg Inc Screen', 58);
insert into screens (screen_name, view_id) values ('Runolfsson-Braun Screen', 24);
insert into screens (screen_name, view_id) values ('Rowe and Sons Screen', 90);
insert into screens (screen_name, view_id) values ('Frami-Abshire Screen', 54);
insert into screens (screen_name, view_id) values ('Carroll, Leannon and King Screen', 94);
insert into screens (screen_name, view_id) values ('Runte-Beahan Screen', 5);
insert into screens (screen_name, view_id) values ('Marvin Inc Screen', 68);
insert into screens (screen_name, view_id) values ('Volkman, Labadie and Ferry Screen', 90);
insert into screens (screen_name, view_id) values ('VonRueden-Wolf Screen', 98);
insert into screens (screen_name, view_id) values ('Hagenes Group Screen', 22);
insert into screens (screen_name, view_id) values ('Effertz-Schaefer Screen', 10);
insert into screens (screen_name, view_id) values ('Tromp-Lehner Screen', 1);
insert into screens (screen_name, view_id) values ('Grant-Turner Screen', 74);
insert into screens (screen_name, view_id) values ('Kozey-Greenholt Screen', 12);
insert into screens (screen_name, view_id) values ('Wintheiser-Bartoletti Screen', 18);
insert into screens (screen_name, view_id) values ('Becker-Huel Screen', 15);
insert into screens (screen_name, view_id) values ('Smith LLC Screen', 71);
insert into screens (screen_name, view_id) values ('Hessel-Schroeder Screen', 62);
insert into screens (screen_name, view_id) values ('Hayes, Morissette and Kohler Screen', 10);
insert into screens (screen_name, view_id) values ('Shields Group Screen', 36);
insert into screens (screen_name, view_id) values ('Will-Kovacek Screen', 63);
insert into screens (screen_name, view_id) values ('Morar and Sons Screen', 52);
insert into screens (screen_name, view_id) values ('Kirlin-Yundt Screen', 27);
insert into screens (screen_name, view_id) values ('Zieme-Williamson Screen', 24);
insert into screens (screen_name, view_id) values ('Labadie LLC Screen', 13);
insert into screens (screen_name, view_id) values ('Parker-Grant Screen', 62);
insert into screens (screen_name, view_id) values ('Ratke-Brekke Screen', 22);
insert into screens (screen_name, view_id) values ('Conn-Bosco Screen', 32);
insert into screens (screen_name, view_id) values ('Tremblay Inc Screen', 61);
insert into screens (screen_name, view_id) values ('Veum-Dooley Screen', 50);
insert into screens (screen_name, view_id) values ('Kovacek, Fritsch and Wilderman Screen', 79);
insert into screens (screen_name, view_id) values ('Torphy, Kutch and Weissnat Screen', 5);
insert into screens (screen_name, view_id) values ('Wisozk and Sons Screen', 47);
insert into screens (screen_name, view_id) values ('Stamm-Larkin Screen', 93);
insert into screens (screen_name, view_id) values ('Pacocha and Sons Screen', 70);
insert into screens (screen_name, view_id) values ('Heathcote-Champlin Screen', 50);
insert into screens (screen_name, view_id) values ('Carter, Reynolds and Lehner Screen', 52);
insert into screens (screen_name, view_id) values ('Corwin, Schneider and Pfannerstill Screen', 27);
insert into screens (screen_name, view_id) values ('Tromp-Stanton Screen', 43);
insert into screens (screen_name, view_id) values ('Corkery, Greenfelder and McCullough Screen', 92);
insert into screens (screen_name, view_id) values ('Schamberger, Adams and Fisher Screen', 12);
insert into screens (screen_name, view_id) values ('Nienow-Miller Screen', 63);
insert into screens (screen_name, view_id) values ('Emmerich and Sons Screen', 81);
insert into screens (screen_name, view_id) values ('Bruen, Blanda and Predovic Screen', 21);
insert into screens (screen_name, view_id) values ('Emard-Bruen Screen', 14);
insert into screens (screen_name, view_id) values ('Rowe LLC Screen', 22);
insert into screens (screen_name, view_id) values ('Klocko-Green Screen', 73);
insert into screens (screen_name, view_id) values ('Abshire-Lebsack Screen', 95);
insert into screens (screen_name, view_id) values ('Zulauf-Breitenberg Screen', 19);
insert into screens (screen_name, view_id) values ('McKenzie-Davis Screen', 88);
insert into screens (screen_name, view_id) values ('D''Amore, Borer and Macejkovic Screen', 5);
insert into screens (screen_name, view_id) values ('Deckow, Berge and Kassulke Screen', 38);
insert into screens (screen_name, view_id) values ('Gislason and Sons Screen', 19);
insert into screens (screen_name, view_id) values ('Schumm-Crooks Screen', 17);
insert into screens (screen_name, view_id) values ('Sipes-Lehner Screen', 84);
insert into screens (screen_name, view_id) values ('Schulist LLC Screen', 39);
insert into screens (screen_name, view_id) values ('Howe-Jenkins Screen', 59);
insert into screens (screen_name, view_id) values ('Borer, Terry and Weissnat Screen', 90);
insert into screens (screen_name, view_id) values ('Krajcik, Upton and Feeney Screen', 41);
insert into screens (screen_name, view_id) values ('Boyle, Thompson and Borer Screen', 76);
insert into screens (screen_name, view_id) values ('Gleichner-Spinka Screen', 87);
insert into screens (screen_name, view_id) values ('Swift-Hermiston Screen', 5);
insert into screens (screen_name, view_id) values ('Kuphal, Boyle and Senger Screen', 71);
insert into screens (screen_name, view_id) values ('Kris, Champlin and Emard Screen', 14);
insert into screens (screen_name, view_id) values ('Dicki, Konopelski and Dooley Screen', 17);
insert into screens (screen_name, view_id) values ('Bernhard-Kuhn Screen', 54);
insert into screens (screen_name, view_id) values ('VonRueden-Donnelly Screen', 36);
insert into screens (screen_name, view_id) values ('Koch, Jaskolski and Huels Screen', 98);
insert into screens (screen_name, view_id) values ('Bogisich-Monahan Screen', 83);
insert into screens (screen_name, view_id) values ('Mitchell Inc Screen', 11);
insert into screens (screen_name, view_id) values ('McKenzie and Sons Screen', 88);
insert into screens (screen_name, view_id) values ('Hahn and Sons Screen', 88);
insert into screens (screen_name, view_id) values ('Beatty, Murphy and Aufderhar Screen', 10);
insert into screens (screen_name, view_id) values ('Miller, Lakin and Rau Screen', 99);
insert into screens (screen_name, view_id) values ('Schaefer-Gislason Screen', 39);
insert into screens (screen_name, view_id) values ('Fisher, Gottlieb and Schowalter Screen', 28);
insert into screens (screen_name, view_id) values ('Rosenbaum-Pagac Screen', 2);
insert into screens (screen_name, view_id) values ('Harvey, Haag and Schuster Screen', 92);
insert into screens (screen_name, view_id) values ('Smitham LLC Screen', 69);
insert into screens (screen_name, view_id) values ('Veum, Russel and Reichert Screen', 96);
insert into screens (screen_name, view_id) values ('Towne Inc Screen', 81);
insert into screens (screen_name, view_id) values ('Bailey, Herman and Moore Screen', 97);
insert into screens (screen_name, view_id) values ('Wisozk-Gleichner Screen', 74);
insert into screens (screen_name, view_id) values ('Abernathy-Moore Screen', 35);
insert into screens (screen_name, view_id) values ('Shields LLC Screen', 36);
insert into screens (screen_name, view_id) values ('Botsford, Denesik and Heidenreich Screen', 51);
insert into screens (screen_name, view_id) values ('Zboncak, Dare and Flatley Screen', 28);
insert into screens (screen_name, view_id) values ('Wuckert Inc Screen', 41);
insert into screens (screen_name, view_id) values ('Torphy and Sons Screen', 77);
insert into screens (screen_name, view_id) values ('Erdman-Dooley Screen', 44);
insert into screens (screen_name, view_id) values ('Kozey LLC Screen', 51);
insert into screens (screen_name, view_id) values ('Braun and Sons Screen', 60);
insert into screens (screen_name, view_id) values ('Yundt, Bosco and Purdy Screen', 39);
insert into screens (screen_name, view_id) values ('Kessler-Maggio Screen', 40);
insert into screens (screen_name, view_id) values ('Beatty Inc Screen', 79);
insert into screens (screen_name, view_id) values ('Denesik-Pfannerstill Screen', 7);
insert into screens (screen_name, view_id) values ('Haley and Sons Screen', 7);
insert into screens (screen_name, view_id) values ('Luettgen-Yost Screen', 77);
insert into screens (screen_name, view_id) values ('Kuvalis, Schroeder and Conroy Screen', 40);
insert into screens (screen_name, view_id) values ('Bechtelar, Bogan and Bashirian Screen', 35);
insert into screens (screen_name, view_id) values ('Legros-Reynolds Screen', 57);
insert into screens (screen_name, view_id) values ('Kozey-Rau Screen', 40);
insert into screens (screen_name, view_id) values ('DuBuque, Shields and Hoeger Screen', 49);
insert into screens (screen_name, view_id) values ('Tillman, Frami and Prosacco Screen', 50);
insert into screens (screen_name, view_id) values ('Mohr Inc Screen', 22);
insert into screens (screen_name, view_id) values ('Torphy, Feest and Stiedemann Screen', 41);
insert into screens (screen_name, view_id) values ('Mann-Kutch Screen', 88);
insert into screens (screen_name, view_id) values ('Hessel-Daugherty Screen', 84);
insert into screens (screen_name, view_id) values ('MacGyver LLC Screen', 73);
insert into screens (screen_name, view_id) values ('Hahn Inc Screen', 80);
insert into screens (screen_name, view_id) values ('Larson, McLaughlin and Konopelski Screen', 64);
insert into screens (screen_name, view_id) values ('Goyette, Jaskolski and Oberbrunner Screen', 98);
insert into screens (screen_name, view_id) values ('Yost, Considine and Greenholt Screen', 79);
insert into screens (screen_name, view_id) values ('Towne-Schaden Screen', 5);
insert into screens (screen_name, view_id) values ('MacGyver and Sons Screen', 73);
insert into screens (screen_name, view_id) values ('Crona LLC Screen', 67);
insert into screens (screen_name, view_id) values ('Farrell, Leannon and Johnston Screen', 62);
insert into screens (screen_name, view_id) values ('Greenfelder, Feest and Dicki Screen', 11);
insert into screens (screen_name, view_id) values ('Shanahan-Effertz Screen', 44);
insert into screens (screen_name, view_id) values ('Tremblay-Leffler Screen', 23);
insert into screens (screen_name, view_id) values ('Casper, Toy and Greenholt Screen', 34);
insert into screens (screen_name, view_id) values ('Tillman and Sons Screen', 82);
insert into screens (screen_name, view_id) values ('Jacobson, Thiel and Kilback Screen', 30);
insert into screens (screen_name, view_id) values ('Lebsack and Sons Screen', 41);
insert into screens (screen_name, view_id) values ('Wintheiser, Robel and Farrell Screen', 78);
insert into screens (screen_name, view_id) values ('Koelpin Inc Screen', 91);
insert into screens (screen_name, view_id) values ('Littel-Wisoky Screen', 47);
insert into screens (screen_name, view_id) values ('Grady, Rohan and Reinger Screen', 4);
insert into screens (screen_name, view_id) values ('Hilll, Schaden and Nikolaus Screen', 30);
insert into screens (screen_name, view_id) values ('Stiedemann and Sons Screen', 57);
insert into screens (screen_name, view_id) values ('Little, Powlowski and McLaughlin Screen', 17);
insert into screens (screen_name, view_id) values ('Cormier-Borer Screen', 41);
insert into screens (screen_name, view_id) values ('Howell-Kling Screen', 66);
insert into screens (screen_name, view_id) values ('Satterfield, Spinka and Ondricka Screen', 28);
insert into screens (screen_name, view_id) values ('Bernhard Group Screen', 47);
insert into screens (screen_name, view_id) values ('Gerhold-Kuhn Screen', 30);
insert into screens (screen_name, view_id) values ('Altenwerth-Zulauf Screen', 11);
insert into screens (screen_name, view_id) values ('Bosco, Jacobson and Beer Screen', 86);
insert into screens (screen_name, view_id) values ('Balistreri LLC Screen', 12);
insert into screens (screen_name, view_id) values ('Morar LLC Screen', 90);
insert into screens (screen_name, view_id) values ('Rice-Borer Screen', 84);
insert into screens (screen_name, view_id) values ('Bernhard, Haag and Gleason Screen', 22);
insert into screens (screen_name, view_id) values ('Keebler, Cole and Lockman Screen', 54);
insert into screens (screen_name, view_id) values ('Kihn Inc Screen', 85);
insert into screens (screen_name, view_id) values ('Erdman, Feest and Fritsch Screen', 95);
insert into screens (screen_name, view_id) values ('Kautzer, Kassulke and Jast Screen', 59);
insert into screens (screen_name, view_id) values ('Borer Group Screen', 75);
insert into screens (screen_name, view_id) values ('Klein Group Screen', 93);
insert into screens (screen_name, view_id) values ('Purdy Group Screen', 87);
insert into screens (screen_name, view_id) values ('Kihn, Funk and Jones Screen', 53);
insert into screens (screen_name, view_id) values ('O''Reilly-Ullrich Screen', 57);
insert into screens (screen_name, view_id) values ('Gaylord, Rau and Daugherty Screen', 44);
insert into screens (screen_name, view_id) values ('Renner Inc Screen', 80);
insert into screens (screen_name, view_id) values ('Mayert Group Screen', 94);
insert into screens (screen_name, view_id) values ('Kessler Group Screen', 95);
insert into screens (screen_name, view_id) values ('Lynch-Lowe Screen', 10);
insert into screens (screen_name, view_id) values ('Konopelski, Toy and Pfannerstill Screen', 34);
insert into screens (screen_name, view_id) values ('Keebler-Stiedemann Screen', 3);
insert into screens (screen_name, view_id) values ('Kohler Group Screen', 37);
insert into screens (screen_name, view_id) values ('Mills, Osinski and Price Screen', 59);
insert into screens (screen_name, view_id) values ('Harvey-Huel Screen', 59);
insert into screens (screen_name, view_id) values ('Kulas-Fritsch Screen', 12);
insert into screens (screen_name, view_id) values ('Hickle-Will Screen', 21);
insert into screens (screen_name, view_id) values ('Hayes Group Screen', 74);
insert into screens (screen_name, view_id) values ('Emmerich, Armstrong and Gutkowski Screen', 94);
insert into screens (screen_name, view_id) values ('Kerluke, Runolfsson and Flatley Screen', 57);
insert into screens (screen_name, view_id) values ('Kuhlman, Friesen and Lakin Screen', 66);
insert into screens (screen_name, view_id) values ('Quitzon, Emard and Turcotte Screen', 81);
insert into screens (screen_name, view_id) values ('Bailey-Schneider Screen', 26);
insert into screens (screen_name, view_id) values ('Swaniawski-Cassin Screen', 44);
insert into screens (screen_name, view_id) values ('Hickle-Jakubowski Screen', 11);
insert into screens (screen_name, view_id) values ('Bayer Inc Screen', 70);
insert into screens (screen_name, view_id) values ('Hyatt-Fahey Screen', 55);
insert into screens (screen_name, view_id) values ('Fahey, Bruen and Fahey Screen', 83);
insert into screens (screen_name, view_id) values ('Boehm-Green Screen', 69);
insert into screens (screen_name, view_id) values ('Wisozk Inc Screen', 18);
insert into screens (screen_name, view_id) values ('McClure-Stark Screen', 26);
insert into screens (screen_name, view_id) values ('O''Kon Group Screen', 25);
insert into screens (screen_name, view_id) values ('Davis Group Screen', 19);
insert into screens (screen_name, view_id) values ('Cartwright, Adams and Wehner Screen', 7);
insert into screens (screen_name, view_id) values ('Schimmel and Sons Screen', 75);
insert into screens (screen_name, view_id) values ('Mante-Moen Screen', 21);
insert into screens (screen_name, view_id) values ('Quitzon Inc Screen', 97);